name: rabbitmq_dart_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  mqtt5_client: ^4.6.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
